webtalk_init -webtalk_dir C:/Users/augus/Documents/Fundacion Fulgor/Digital design Verilog RTL Course/Designs/parallel_conv_5_3/parallel_conv_5_3.sim/sim_1/behav/xsim/xsim.dir/parallel_conv_5_3_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Nov 24 21:53:49 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "5f8c4234-62a9-4ae4-9fc6-c9bba8466aeb" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "52f2c7ef8d3d4fe280168e70e9c0d534" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "266" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i3-6006U CPU @ 2.00GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1992 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "3 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.12_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "6500_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3602805855 -regid "" -xml C:/Users/augus/Documents/Fundacion Fulgor/Digital design Verilog RTL Course/Designs/parallel_conv_5_3/parallel_conv_5_3.sim/sim_1/behav/xsim/xsim.dir/parallel_conv_5_3_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/augus/Documents/Fundacion Fulgor/Digital design Verilog RTL Course/Designs/parallel_conv_5_3/parallel_conv_5_3.sim/sim_1/behav/xsim/xsim.dir/parallel_conv_5_3_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/augus/Documents/Fundacion Fulgor/Digital design Verilog RTL Course/Designs/parallel_conv_5_3/parallel_conv_5_3.sim/sim_1/behav/xsim/xsim.dir/parallel_conv_5_3_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
